import { BaseContact } from './types';

export const STAFF_DATA: BaseContact[] = [
  { name: 'Moffett, Misty', info: 'Landing Building Reception Desk', phone: '253-0303', category: 'Staff', role: 'Reception' },
  { name: 'Bigelow, Jan', info: 'President/Chief Executive Officer', phone: '565-6507', category: 'Staff', role: 'Executive' },
  { name: 'Becker, John', info: 'Executive VP/Chief Operating Officer', phone: '253-9678', category: 'Staff', role: 'Executive' },
  { name: 'Browder, Courtney', info: 'Director of Administration', phone: '565-6500', category: 'Staff', role: 'Administration' },
  { name: 'Cason, Britnee', info: 'Director of Wellness', phone: '565-6547', category: 'Staff', role: 'Wellness' },
  { name: 'Denney, Ashley', info: 'Resident Experience Manager', phone: '253-9689', category: 'Staff', role: 'Management' },
  { name: 'McGregor, Kelly', info: 'IL Activities Manager', phone: '565-6529', category: 'Staff', role: 'Activities' },
  { name: 'Segal, Rose', info: 'AL Activities Coordinator', phone: '258-2163', category: 'Staff', role: 'Activities' },
  { name: 'Mendes, Jahi', info: 'Community Center & Arts Coordinator', phone: '790-2643', category: 'Staff', role: 'Activities' },
  { name: 'Armstead, Clay', info: 'Event Porter', phone: '565-0591', category: 'Staff', role: 'Events' },
  { name: 'Sander, Paul', info: 'Director of Adult Day Services', phone: '565-6542', category: 'Staff', role: 'Management' },
  { name: 'Belcher, Nora', info: 'Office Coordinator', phone: '565-6544', category: 'Staff', role: 'Administration' },
  { name: 'Merrill, Colleen', info: 'Director of Assisted Living', phone: '258-2175', category: 'Staff', role: 'Management' },
  { name: 'Martin, Debbie', info: 'Resident Engagement Manager', phone: '258-2112', category: 'Staff', role: 'Management' },
  { name: 'Coveney, Bree', info: 'AL Sales Advisor', phone: '258-2166', category: 'Staff', role: 'Sales' },
  { name: 'Cotton, Christina', info: 'Staff Development Nurse', phone: '790-2646', category: 'Staff', role: 'Nursing' },
  { name: 'Williams, Angie', info: 'Quality Assessment Nurse', phone: '258-2197', category: 'Staff', role: 'Nursing' },
  { name: 'Hicks, Stephanie', info: 'Administrative Assistant (AL)', phone: '253-8801', category: 'Staff', role: 'Administration' },
  { name: 'Dooley, Jennifer', info: 'AL Admissions Coordinator', phone: '565-6501', category: 'Staff', role: 'Admissions' },
  { name: 'Davis, Becca', info: 'Social Work Manager', phone: '565-6538', category: 'Staff', role: 'Social Services' },
  { name: 'Haywood, Kailey', info: 'Medical Records', phone: '565-6527', category: 'Staff', role: 'Records' },
  { name: 'Osheim-Owen, Jennifer', info: 'Chaplain', phone: '253-9679', category: 'Staff', role: 'Chaplain' },
  { name: 'Ferguson, Frank', info: 'Chaplain', phone: '253-9685', category: 'Staff', role: 'Chaplain' },
  { name: 'Wolfe, Sally', info: 'Chief Development Officer', phone: '253-9677', category: 'Staff', role: 'Development' },
  { name: 'Changa, Devin', info: 'Fundraising Coordinator', phone: '253-9682', category: 'Staff', role: 'Development' },
  { name: 'Stephens, Allen', info: 'Director of Dining Services', phone: '565-6531', category: 'Staff', role: 'Dining' },
  { name: 'Fleming, Nakia', info: 'Executive Chef', phone: '253-9674', category: 'Staff', role: 'Dining' },
  { name: 'Veney, Lynasia', info: 'AL Operations Manager', phone: '258-9687', category: 'Staff', role: 'Dining' },
  { name: 'Cheeks, Kimberly', info: 'Dining Room Manager', phone: '253-9723', category: 'Staff', role: 'Dining' },
  { name: 'Artiles, Lewiss', info: 'Catering and Retail Manager', phone: '903-2647', category: 'Staff', role: 'Dining' },
  { name: 'Bowling, Emily', info: 'Dietitian', phone: '585-7753', category: 'Staff', role: 'Dining' },
  { name: 'Legaspi, Luci', info: 'Finance Manager', phone: '585-7751', category: 'Staff', role: 'Finance' },
  { name: 'Story, Carl', info: 'Director of Facilities', phone: '253-9684', category: 'Staff', role: 'Facilities' },
  { name: 'Dibble, Lisa', info: 'Assistant Director of Facilities', phone: '565-6518', category: 'Staff', role: 'Facilities' },
  { name: 'Williams, Paul', info: 'Field Manager', phone: '565-6503', category: 'Staff', role: 'Facilities' },
  { name: 'McMullen, Cassandra', info: 'Service Coordinator', phone: '565-6515', category: 'Staff', role: 'Facilities' },
  { name: 'Drewery, Justin', info: 'Grounds and Landscaping Manager', phone: '585-7745', category: 'Staff', role: 'Grounds' },
  { name: 'Kalemdaroglu, Cenk', info: 'Health Care Administrator', phone: '258-2174', category: 'Staff', role: 'Management' },
  { name: 'Mutchie, Eric', info: 'Director of Nursing (DON)', phone: '258-2165', category: 'Staff', role: 'Nursing' },
  { name: 'Payne, Heather', info: 'Social Services Discharge Coordinator', phone: '253-9715', category: 'Staff', role: 'Social Services' },
  { name: 'Deaver, Barbara', info: 'Admissions Coordinator', phone: '565-6524', category: 'Staff', role: 'Admissions' },
  { name: 'Cobb, Jill', info: 'Administrative Assistant (HRC)', phone: '790-2644', category: 'Staff', role: 'Administration' },
  { name: 'Khajanchi, Shubham', info: 'Director, Rehabilitation', phone: '258-2129', category: 'Staff', role: 'Rehab' },
  { name: 'Cheely, Aaron', info: 'Health Club Manager', phone: '565-6543', category: 'Staff', role: 'Wellness' },
  { name: 'LeDuc, Cassandra', info: 'Office Coordinator', phone: '565-6545', category: 'Staff', role: 'Administration' },
  { name: 'Shepard, Betsy', info: 'Aquatics Office', phone: '565-6546', category: 'Staff', role: 'Wellness' },
  { name: 'Faggins, Corey', info: 'Lead Fitness Room Assistant', phone: '585-7744', category: 'Staff', role: 'Wellness' },
  { name: 'Rogers, Karien', info: 'Housekeeping Manager', phone: '253-9676', category: 'Staff', role: 'Housekeeping' },
  { name: 'Lightfoot, Marita', info: 'Housekeeping Lead', phone: '253-9675', category: 'Staff', role: 'Housekeeping' },
  { name: 'Piggott, Val', info: 'Housekeeping Lead (IL)', phone: '253-9722', category: 'Staff', role: 'Housekeeping' },
  { name: 'Maddox, Stephanie', info: 'EVS Floor Tech Lead', phone: '790-2642', category: 'Staff', role: 'Housekeeping' },
  { name: 'Young, Camille', info: 'Clinic Nurse Practitioner', phone: '565-6525', category: 'Staff', role: 'Nursing' },
  { name: 'Adams, Vonnie', info: 'Chief Clinical Officer', phone: '253-9673', category: 'Staff', role: 'Executive' },
  { name: 'Rigney, Barbara', info: 'Medical Office Coordinator', phone: '565-6525', category: 'Staff', role: 'Nursing' },
  { name: 'Martin, Kim', info: 'Nurse', phone: '564-1104', category: 'Staff', role: 'Nursing' },
  { name: 'Mitchell, Kimberly', info: 'Resident Services Coordinator', phone: '564-1100', category: 'Staff', role: 'Resident Services' },
  { name: 'Hallett, Mara', info: 'Resident Services Coordinator', phone: '258-2198', category: 'Staff', role: 'Resident Services' },
  { name: 'Gaudio, Pattie', info: 'Cognitive Services Manager', phone: '585-7743', category: 'Staff', role: 'Cognitive Services' },
  { name: 'Morgan, Emma', info: 'Cognitive Services Assistant', phone: '258-2169', category: 'Staff', role: 'Cognitive Services' },
  { name: 'Knight, Charlie', info: 'Director of IT', phone: '565-6558', category: 'Staff', role: 'IT' },
  { name: 'Pribble, Jonathan', info: 'Network Administrator', phone: '258-2161', category: 'Staff', role: 'IT' },
  { name: 'Bates, Lisa', info: 'Chief Marketing Officer', phone: '253-9671', category: 'Staff', role: 'Marketing' },
  { name: 'Bradley, Stephanie', info: 'Assistant Director of Marketing', phone: '253-9670', category: 'Staff', role: 'Marketing' },
  { name: 'Gordon, John', info: 'Assistant Director of Marketing', phone: '565-6506', category: 'Staff', role: 'Marketing' },
  { name: 'Twing, Lauren', info: 'Social Media Specialist', phone: '253-9711', category: 'Staff', role: 'Marketing' },
  { name: 'Drewery, Krystle', info: 'Relocation Coordinator', phone: '585-7740', category: 'Staff', role: 'Marketing' },
  { name: 'Indoe, Meghan', info: 'Marketing & Sales Assistant', phone: '253-9680', category: 'Staff', role: 'Marketing' },
  { name: 'Burcher, Joshua', info: 'Purchasing Manager', phone: '565-6536', category: 'Staff', role: 'Purchasing' },
  { name: 'Bonney, Jonathan', info: 'Purchasing Agent', phone: '565-6554', category: 'Staff', role: 'Purchasing' },
  { name: 'Rodriguez, Laura', info: 'Cove Crest/Namaste Manager', phone: '585-7754', category: 'Staff', role: 'Management' },
  { name: 'Hamer, Rachael', info: 'Beauty Salon - LB', phone: '253-9686', category: 'Staff', role: 'Services' },
  { name: 'Karp, Pam', info: 'Landing Store Manager', phone: '565-6523', category: 'Staff', role: 'Services' },
  { name: 'Dille, Todd', info: 'Security Manager', phone: '585-7742', category: 'Staff', role: 'Security' },
  { name: 'Becke, Rachel', info: 'Chief Talent Officer', phone: '258-2164', category: 'Staff', role: 'Human Resources' },
  { name: 'Steward, Nataly', info: 'Talent Management Assistant', phone: '565-6522', category: 'Staff', role: 'Human Resources' },
  { name: 'Berry, Janet', info: 'Talent Management Business Partner', phone: '258-2228', category: 'Staff', role: 'Human Resources' },
  { name: 'Easley, Johanna', info: 'Compensation & Benefits Specialist', phone: '565-6514', category: 'Staff', role: 'Human Resources' },
  { name: 'Foley, Amanda', info: 'Recruiting & Retention Manager', phone: '565-6552', category: 'Staff', role: 'Human Resources' },
  { name: 'Clarke, Andrea', info: 'Transportation Supervisor', phone: '258-2229', category: 'Staff', role: 'Transportation' },
];